.github/workflows/test-cli.yml
tools/cli-rs/Cargo.toml
tools/cli-rs/src/main.rs

This PR adds:
- A new bpftime cli named `bpftime` which is located in `tools/cli-rs`. It has the ability to inject server or agent into applications and run them. It can also be statically linked which provides a more convenient way to distribute
- Related workflows to test the new CLI. They are in `test-cli.yml`. The workflow will build & install runtime and cli, and invokes cli to inject server and agent, and test if them exist successfully.

Tools: add a new CLI in rust and related CI tests

---

.github/workflows/test-verifier.yml
Makefile
benchmark/syscall/README.md
runtime/agent-transformer/CMakeLists.txt
runtime/agent-transformer/agent-transformer.cpp
runtime/agent-transformer/text_segment_transformer.cpp
runtime/include/bpftime.hpp
runtime/include/bpftime_shm.hpp
runtime/include/syscall_table.hpp
runtime/object/bpf_object.cpp
runtime/src/attach/attach_internal.cpp
runtime/src/attach/bpf_attach_ctx.cpp
runtime/src/bpf_helper.cpp
runtime/src/bpftime_internal.h
runtime/src/bpftime_prog.cpp
runtime/src/bpftime_shm.cpp
runtime/src/ffi.cpp
runtime/src/syscall_table.cpp
runtime/syscall-server/syscall_server.cpp
runtime/test/src/test_attach_uprobe.cpp
runtime/test/src/test_helpers.cpp
runtime/test/src/test_shm_progs_attach.cpp

Closes #15 
This PR uses frida-capstone to decompile assembly in text segment transformer, instead of libopcodes. Thus we don't depend on libopcodes anymore.

Replace libopcodes with frida-capstone

---

runtime/syscall-server/syscall_context.hpp

To avoid polluting other child processes, we unset the `LD_PRELOAD` env var after syscall context being initialized

Remove LD_PRELOAD env var after intializing syscall context

---

.gitignore
runtime/agent/agent.cpp
runtime/src/attach/bpf_attach_ctx.cpp
runtime/src/bpf_helper.cpp
runtime/src/bpf_map/array_map.cpp
runtime/src/bpf_map/hash_map.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/src/bpftime_shm_internal.hpp
runtime/syscall-server/syscall_server_utils.cpp

includes:
- Forbid the auto initialization of bpf_attach_ctx and bpftime_shm. They will be manually initialized when syscall server was loaded (firstly called sys_bpf) or agent was loaded (before the execution of main function)
- Add a helper bpf_probe_read_user that sslsniff will use
- Fix an null-deref issue of the get next key implementation of array_map
-

Fix some issues that may cause sslsniff not working

---

runtime/src/attach/bpf_attach_ctx.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/src/ffi.cpp
runtime/src/handler/perf_event_handler.cpp
runtime/test/CMakeLists.txt
runtime/test/src/test_attach_hook.cpp
runtime/test/src/test_attach_uprobe.cpp
runtime/test/src/test_shm_progs_attach.cpp
vm/test/include/test_minimal_bpf_host_ffi.h

Use `gum_object_unref` to release the listener object, instead of `gum_free`, when destroying `bpf_attach_ctx`
Closes #32 
Also fixed many warnings when compiling use Release profile

runtime: fix a double-free bug

---

.github/workflows/runtime.yml
.github/workflows/test-cli.yml
.github/workflows/test-examples.yml
.github/workflows/test-runtime.yml
CMakeLists.txt
cmake/libbpf.cmake
runtime/CMakeLists.txt
runtime/bpftime-daemon/CMakeLists.txt

This PR adds CMakeLists that build bpftime-daemon. 
The target name is bpftime_daemon. 
See `runtime/bpftime-daemon/CMakeLists.txt` for detailed usage.
This PR also adds targets that build bpftool and skeleton header

Use cmake to build bpftime-daemon

---

Makefile
benchmark/CMakeLists.txt
benchmark/test_embed.c
cmake/libbpf.cmake
documents/build-and-test.md
runtime/src/attach/attach_manager/frida_attach_manager.cpp
runtime/src/attach/bpf_attach_ctx.cpp
runtime/src/bpf_map/ringbuf_map.cpp

- fix runtime compile error
- fix compile ebpf prog error
- update libbpf version

runtime: fix compile error and docker image error

---

.github/workflows/test-examples.yml

Update examples CI, use only one job to build the runtime. Other matrix jobs receive the prebuilt runtime through artifacts

Update examples CI

---

CONTRIBUTING.md

doc: Create CONTRIBUTING.md

---

README.md

Fix links for webpage. Use abstract address.

docs: fix links for webpage

---

README.md
daemon/bpf_tracer_event.h
daemon/kernel/bpf_tracer.bpf.c
daemon/user/bpf_tracer.cpp
daemon/user/daemon_config.hpp
daemon/user/handle_bpf_event.cpp
daemon/user/handle_bpf_event.hpp
runtime/src/bpftime_shm.cpp
runtime/src/handler/perf_event_handler.cpp

Add tracing of process exec with a minimal duration.
This is used for attaching Uprobe to a new process in the future, just like kernel does.

daemon: add process exec tracing

---

daemon/CMakeLists.txt

daemon: link librt  (Fix issue #73)

---

.github/script/run_example.py
.github/workflows/test-examples.yml
example/libbpf-tools/bashreadline/readline.c
example/libbpf-tools/gethostlatency/gethostlatency.c
example/libbpf-tools/opensnoop/opensnoop.c
example/libbpf-tools/statsnoop/statsnoop.c
example/malloc/malloc.c
example/opensnoop/opensnoop.c
example/sslsniff/sslsniff.c
tools/cli-rs/src/main.rs

This PR implements automatic testing of examples CI, using a python program.
Test process:
- Run server, monitoring the stdout until `bpftime-syscall-server started` appeared, with timeout of at most 15 seconds
- Wait for 10 seconds
- Run victim, monitoring stdout of server until the test-specified signal string appeared, with timeout of at most 15 seconds
Note:
- bashreadline is not supported now

Update examples CI (automatic test)

---

.gitignore
daemon/kernel/bpf_tracer.bpf.c
daemon/user/bpf_tracer.cpp
daemon/user/bpftime_driver.cpp
daemon/user/daemon_config.hpp
daemon/user/main.cpp
example/.gitignore
runtime/src/attach/attach_manager/frida_attach_manager.cpp
runtime/src/attach/bpf_attach_ctx.cpp
runtime/src/bpf_map/shared/hash_map_kernel_user.hpp
runtime/src/bpf_map/shared/percpu_array_map_kernel_user.hpp
runtime/src/handler/handler_manager.cpp
runtime/src/handler/perf_event_handler.cpp
runtime/src/handler/perf_event_handler.hpp
runtime/test/bpf/.gitignore
runtime/test/src/test_shm_progs_attach.cpp
runtime/unit-test/attach/test_filter_attach.cpp
runtime/unit-test/attach/test_replace_attach.cpp
runtime/unit-test/attach/test_uprobe_uretprobe.cpp
runtime/unit-test/attach_with_ebpf/test_attach_filter_with_ebpf.cpp
vm/llvm-jit/src/bpf_jit.cpp

This PR updated bpftime-daemon (both kernel ebpf program and userspace program), and make deepflow's attach to runtime.casgstatus work in userspace.
- Adds uprobe whitelist support. If enabled, only attaches to the specified address will be executed in userspace. Pass `-w ADDR` argument to `bpftime_daemon` to enable this. Multiple arguments is also supported. `-w 0x1234 -w 0x2345`
1. Run `bpftime_daemon`
2. Run the go program to be traced
3. Run `deepflow/rust_example`
4. Use **bpftime attach** to attach to the process

daemon: enable uprobe white list

---

example/.gitignore
runtime/src/bpf_map/shared/array_map_kernel_user.cpp
runtime/src/bpf_map/shared/array_map_kernel_user.hpp
runtime/src/bpftime_prog.cpp
runtime/src/bpftime_shm.cpp
vm/llvm-jit/src/bpf_jit.cpp
vm/llvm-jit/src/bpf_jit_compile_module.cpp
vm/llvm-jit/src/bpf_jit_helpers.h
vm/llvm-jit/src/ebpf_vm.cpp

The bug could be seen at https://github.com/eunomia-bpf/bpftime/blob/5e47de098a3dc2db3811afc2c7b897c85b0543aa/vm/llvm-jit/src/bpf_jit.cpp#L78
I mistyped the function address, causing all lddw helpers were registered to the same native function. This PR fixes it, and adds a number of log statements

vm: fix lddw helper definition bug of `llvm-jit` 

---

runtime/src/bpf_helper.cpp

- bpf_get_current_pid_tgid returns the `PID` of the running task (a.k.a, thread) and the thread group id of it.
Kernel treats indentifion ID of each thread as its PID, and all threads belonging to the same process shares the same thread group id. So the TGID kernel thinks could be retrived from userspace using `getpid` (which returns thread group id of the current thread, in fact). and the PID kernel thinks could be retrived using `gettid` from the userspace.

runtime: fix incorrect implementation in`bpftime_get_current_pid_tgid`

---

.github/workflows/test-runtime.yml
.gitignore
.vscode/launch.json
README.md
runtime/include/bpftime_shm.hpp
runtime/src/attach/bpf_attach_ctx.cpp
runtime/src/bpf_map/README.md
runtime/src/bpftime_prog.cpp
runtime/src/bpftime_shm.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/src/bpftime_shm_internal.hpp

Add mpk support for memory protect

runtime: add mpk support

---

README.md

Sorry for the noise, just happened to notice this, hope you don't mind.

Fix a README.md typo

---

.github/script/run_example.py
runtime/src/bpftime_shm.cpp
runtime/src/handler/perf_event_handler.hpp

This PR fixes the implementation of `epoll_wait` in syscall server, so make bpftrace exit properly.
In kernel, syscall `epoll_wait` could be interrupted by signal, when either no requests were received, or the timeout expired. 
In the previous `epoll_wait` of syscall-server, we doesn't implement similar things. So when signals were devilered during the execution of `epoll_wait`, they were handled normally (e.g directly call the signal handler).
In the current implementation, we block the develivery of SIGINT and SIGTERM (more could be added after suitable tests) during the execution of epoll_wait, but unblock them when epoll_wait is sleeping. epoll_wait will use sigtimedwait to wait for SIGINT and SIGTERM when no requests were received. Once these signal were develivered when sleeping, we …

syscall_server: fix epoll_wait implementation

---

runtime/src/attach/attach_manager/frida_attach_manager.cpp
runtime/src/attach/attach_manager/frida_attach_manager.hpp
runtime/unit-test/attach/test_filter_attach.cpp
runtime/unit-test/attach/test_replace_attach.cpp
runtime/unit-test/attach_with_ebpf/test_attach_filter_with_ebpf.cpp

This PR replaces the using of `shared_ptr` with `unique_ptr`, and replaces the usage of `weak_ptr` with raw pointers, in attach manager

runtime: remove usage of weak_ptr in attach manager

---

.github/script/run_example.py
.github/workflows/test-examples.yml
example/libbpf-tools/mountsnoop/.gitignore
example/libbpf-tools/mountsnoop/Makefile
example/libbpf-tools/mountsnoop/mountsnoop.bpf.c
example/libbpf-tools/mountsnoop/mountsnoop.c
example/libbpf-tools/mountsnoop/mountsnoop.h
example/libbpf-tools/mountsnoop/victim.c
runtime/src/syscall_table.cpp

This PR adds an example mountsnoop. It utilizes syscall  tracepoint to trace call to mount/umount2, and prints the details in userspace program

example: add mountsnoop from libbpf-tools

---

.github/workflows/test-examples.yml
example/libbpf-tools/sigsnoop/.gitignore
example/libbpf-tools/sigsnoop/Makefile
example/libbpf-tools/sigsnoop/sigsnoop.bpf.c
example/libbpf-tools/sigsnoop/sigsnoop.c
example/libbpf-tools/sigsnoop/sigsnoop.h
example/libbpf-tools/sigsnoop/victim.cpp

Adds sigsnoop, which is an example that traces call to kill/pkill/tgkill

example: add sigsnoop from libbpf-tools

---

daemon/user/bpftime_driver.cpp
example/malloc/README.md
runtime/include/bpftime_shm.hpp
runtime/src/bpftime_shm.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/syscall-server/README.md
runtime/syscall-server/syscall_context.cpp
runtime/syscall-server/syscall_context.hpp

Currently, if we want running uprobe with kprobe, we need to use the daemon. This PR make LD_PRELOAD server can run krpobe or use kernel verifier.
Also improve documents.

runtime: enable syscall server to load and run cross boundary programs.

---

runtime/src/attach/attach_manager/base_attach_manager.hpp
runtime/src/attach/attach_manager/frida_attach_manager.cpp
runtime/src/attach/attach_manager/frida_attach_manager.hpp
runtime/src/attach/bpf_attach_ctx.cpp
runtime/test/src/test_attach_replace.cpp
runtime/unit-test/CMakeLists.txt
runtime/unit-test/attach/test_filter_attach_with_override.cpp
runtime/unit-test/attach/test_replace_attach_with_override.cpp
runtime/unit-test/attach_with_ebpf/test_attach_filter_with_ebpf.cpp

This PR removes the implementation of attach type replace in the attach manager, and modifies tests that shipped with replace to override. 
Replace and filter were unified to override now. The override callback was performed before the hooked function's execution. It has access to the arguments, and could override the return value of the hooked function using `bpftime_set_retval`. If `bpftime_set_retval` was called, the original function will not be executed. Otherwise, the execution of the hooked function was not affected.
Closes #112

runtime: remove attach type replace, rename filter to override

---

.github/workflows/test-examples.yml
example/usdt_minimal/.gitignore
example/usdt_minimal/Makefile
example/usdt_minimal/README.md
example/usdt_minimal/usdt_minimal.bpf.c
example/usdt_minimal/usdt_minimal.c
example/usdt_minimal/victim.cpp
runtime/include/bpftime_prog.hpp
runtime/include/bpftime_shm.hpp
runtime/src/attach/bpf_attach_ctx.cpp
runtime/src/attach/bpf_attach_syscall.cpp
runtime/src/bpf_helper.cpp
runtime/src/bpftime_prog.cpp
runtime/src/bpftime_shm.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/src/bpftime_shm_internal.hpp
runtime/src/bpftime_shm_json.cpp
runtime/src/handler/handler_manager.cpp
runtime/src/handler/prog_handler.cpp
runtime/src/handler/prog_handler.hpp
runtime/syscall-server/syscall_context.cpp
runtime/syscall-server/syscall_server_main.cpp
runtime/test/src/test_shm_progs_attach.cpp
runtime/unit-test/test_bpftime_shm_json.cpp
vm/llvm-jit/src/llvm/compiler.cpp
vm/test-runner/CMakeLists.txt
vm/test-runner/main.cpp

Closes #135 
> On x86_64, a usdt tracepoint was corresponded to a nop instruction in the code. So we may hook this instruction to implement userspace USDT I've tested with GumInvocationListener of frida gum, it works well when attached to the address of the nop instruction.
> 
> So things we need to add USDT support are:
> 
> * logic to parse ELF and extract USDT definitions
> 
> Other logics would be similar to uprobe, and can even be reused

runtime: implement userspace USDT

---

.github/workflows/test-llvm-jit.yml
CMakeLists.txt
README.md
vm/CMakeLists.txt
vm/Makefile
vm/README.md
vm/cli/main.cpp
vm/llvm-jit/.gitignore
vm/llvm-jit/CMakeLists.txt
vm/llvm-jit/Makefile
vm/llvm-jit/README.md
vm/llvm-jit/example/main-bpf-conformance.cpp
vm/llvm-jit/src/llvm/llvm_jit_context.cpp
vm/llvm-jit/unit-test/CMakeLists.txt
vm/llvm-jit/unit-test/llvm-aot.cpp

Fixes llvm compile as a standalone library:
- fix documents description
- fix cmake dependence
- add ci for compile

vm: fix llvm as a standalone library

---

Makefile
benchmark/test_embed.c
example/malloc/malloc.c
example/tailcall_minimal/tailcall_minimal.c
example/usdt_minimal/victim.cpp
runtime/agent-transformer/text_segment_transformer.cpp
runtime/src/attach/attach_internal.hpp
runtime/src/attach/bpf_attach_ctx.cpp
runtime/src/attach/bpf_attach_syscall.cpp
runtime/src/bpf_map/userspace/prog_array.cpp
runtime/src/bpf_map/userspace/ringbuf_map.cpp
runtime/src/handler/perf_event_handler.cpp
runtime/unit-test/attach/test_filter_attach_with_override.cpp
runtime/unit-test/attach/test_replace_attach_with_override.cpp
runtime/unit-test/attach/test_uprobe_uretprobe.cpp

- Hardware: M1 Macbook Air w/ Ubuntu 23.04 running in QEMU

Attempt to add arm64 support

---

tools/cli-cpp/main.cpp

Fixes #181
I built and ran some Java programs manually.
```
sudo /root/.bpftime/bpftime start /tmp/jdk-11.0.19/bin/java  -XX:+UseThirdPartyHeap -Xms100M -Xmx100M -jar /usr/share/benchmarks/dacapo/dacapo-23.11-chopin.jar fop
[2024-01-28 03:48:57.447] [info] [agent.cpp:66] Entering bpftime agent
[2024-01-28 03:48:57.447] [info] [bpftime_shm_internal.cpp:618] Global shm constructed. shm_open_type 1 for bpftime_maps_shm
[2024-01-28 03:48:57.448] [info] [agent.cpp:81] Initializing agent..
[2024-01-28 03:48:57][info][1577983] Executable path: /tmp/jdk-11.0.19/bin/java
[2024-01-28 03:48:57][info][1577983] Attached 1 uprobe programs to function 7f60607b4f11
[2024-01-28 03:48:57][info][1577983] Executable path: /tmp/jdk-11.0.19/bin/java
[2024-01-28 03:48:57][info][1577983] Attached 1 uprobe …
```

Capture remaining arguments for bpftime start

---

example/goroutine/go-server-http/.gitattributes

So that git won't treat that executable file as a text file and modify line endings in it

misc: fix autocrlf for binary file example/goroutine/go-server-http/main

---

attach/frida_uprobe_attach_impl/test/test_attach_with_unified_interface.cpp

Issue was during `docker build`, `frida` tests were failing because of registers being used were only for x86
Fixes #237 
Changed explicit register access to macro definition
- [x ] Bug fix (non-breaking change which fixes an issue)
Ran the whole suite by running `make release` during `docker build`
- Firmware version: MacOS Sonoma 14.2
- Hardware: Macbook Air M2
- Toolchain: 
- SDK:
- [x ] I have performed a self-review of my own code

#237 | hp77 | Make registers arch independent

---

.gitignore
cmake/StandardSettings.cmake
cmake/frida.cmake
runtime/CMakeLists.txt

Adding option to disable shared_maps in CMake
Fixes #251 
Checked if CI is failing or not, previously default was OFF but turned it ON and for users to disable shared_map will require them to turn it off while during ON.

runtime: Add cmake options to control build runtime interact with kernel map

---

attach/frida_uprobe_attach_impl/src/frida_attach_utils.cpp
attach/syscall_trace_attach_impl/src/syscall_table.cpp
attach/syscall_trace_attach_impl/src/syscall_trace_attach_impl.cpp
attach/text_segment_transformer/agent-transformer.cpp
runtime/agent/agent.cpp
runtime/extension/extension_helper.cpp
runtime/src/bpf_helper.cpp
runtime/src/bpf_map/shared/perf_event_array_kernel_user.cpp
runtime/src/bpf_map/userspace/perf_event_array_map.cpp
runtime/src/bpf_map/userspace/prog_array.cpp
runtime/src/bpf_map/userspace/ringbuf_map.cpp
runtime/src/bpftime_shm.cpp
runtime/src/handler/handler_manager.cpp
runtime/src/handler/map_handler.hpp
runtime/src/handler/perf_event_handler.cpp
runtime/src/ufunc.cpp

Added top level exception handlers (try-catch) at:
- Instantiating handlers (boost::interprocess might throw exception like bad_alloc, some constructors might throw exceptions)
- Initializing shared memory (same as above)
- map operations (same as above)
This PR also replaces almost all asserts in runtime with throw std::runtime_error (Most of asserts are in constructors of handlers or maps, so if they were replaced with throws, we could catch whem when instantiating handlers or creating maps)

runtime/agent: Add top level exception handlers

---

attach/frida_uprobe_attach_impl/src/frida_internal_attach_entry.cpp
attach/text_segment_transformer/agent-transformer.cpp
runtime/agent/agent.cpp
runtime/include/bpf_attach_ctx.hpp
runtime/src/attach/bpf_attach_ctx.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/src/bpftime_shm_internal.hpp
runtime/src/handler/handler_manager.hpp
tools/cli/CMakeLists.txt
tools/cli/main.cpp
vm/llvm-jit/include/llvm_bpf_jit.h

Closes #261 
We need a way to revert remote injected attaches
- Agent should revert any attached entries when received SIGUSR1
- After that, agent should unload itself from the injected process, i.e unload the shared object from the memory space of the injected process
- Add subcommand `detach` for bpftime cli
- Every agent instance stores its pid into shared memory, if it was injected through frida
- Agent would register signal handler for `SIGUSR1`, and will call bpf_attach_ctx::destroy_all_attach_links to perform detach
- When we run `bpftime detach`, it reads all pids that was stored in the shared memory, and sends SIGUSR1 to them
- We can't unload the injected agent library. A shared object can't unload itself in its code

runtime/agent: implement detaching

---

vm/llvm-jit/CMakeLists.txt

The root cause of #270 is symbol conflict. Closes #270 
- When bpftime links llvm statically and uses LD_PRELOAD to inject into other program which links LLVM dynamically, the symbol in bpftime will override the symbol linked in the injected program. So bpftime initialized LLVM, and the injected program also initialized LLVM, and their initializing results were put into the same global variable, thus leading to option conflict
There are also two solutions:
- Link LLVM dynamically in bpftime. This is relatively easy. We add a CMake option `ENABLE_LLVM_SHARED` and set it default to be true
- Use version script to limit symbols of LLVM into an individual namespace, so these symbols will not override symbols in the injected program. I've also tried this way but more problems were encountered. …

Make llvm-jit work with bpftrace

---

attach/frida_uprobe_attach_impl/include/frida_attach_private_data.hpp
attach/frida_uprobe_attach_impl/src/frida_attach_private_data.cpp
attach/frida_uprobe_attach_impl/src/frida_uprobe_attach_impl.cpp
tools/bpftimetool/main.cpp

There are two bugs that caused bpftime unable to run bashreadline (example/libbpf-tools/bashreadline)
Closes #277

fix: fix segmentation fault about bashreadline

---

example/sslsniff/sslsniff.c

`sslsniff` was using an hardcoded OpenSSL path by default and ignoring the previously resolved path.

fix: using the openssl resolved path in sslsniff

---

runtime/agent/CMakeLists.txt
runtime/agent/agent.version
runtime/syscall-server/CMakeLists.txt
runtime/syscall-server/syscall-server.version

Closes #184 
Use version script to limit dynamic exported symbols. Now only symbols needed for attaching was exported.
```console
root@mnfe-pve:~/bpftime/example/opensnoop# nm ~/.bpftime/libbpftime-agent.so  -D | grep " T " 
0000000000214c20 T bpftime_agent_main
0000000000214bc0 T bpftime_hooked_main
0000000000216030 T _bpftime__setup_syscall_trace_callback
00000000002155b0 T __libc_start_main
0000000000215f90 T syscall_callback
root@mnfe-pve:~/bpftime# nm -D ~/.bpftime/libbpftime-syscall-server.so | grep " T "
0000000000066ac0 T close
0000000000066720 T epoll_create1
0000000000066580 T epoll_ctl
00000000000664d0 T epoll_wait
00000000000667c0 T ioctl
00000000000669f0 T mmap
0000000000066870 T mmap64
00000000000670b0 T munmap
0000000000066b50 T syscall
```
Non-dynamic symbols won't …

fix: do not override symbols in userland eBPF programs with symbols provided by bpftime's bundled libbpf

---

daemon/user/bpftime_driver.cpp
runtime/CMakeLists.txt
runtime/include/bpftime_config.hpp
runtime/include/bpftime_shm.hpp
runtime/src/bpftime_config.cpp
runtime/src/bpftime_shm.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/syscall-server/syscall_server_utils.cpp
tools/bpftimetool/main.cpp

I have declared `extern size_t BPFTIME_SHARED_MEMORY_SIZE;` inside `bpftime_shm_internal.hpp` and inside `bpftime_shm_internal.cpp` defined the `size_t BPFTIME_SHARED_MEMORY_SIZE = 20; // Default size`
Then inside the cli/main.cpp I have added support for --shared-memory-size.
Fixes #282 
- [✅] New feature (non-breaking change which adds functionality)
- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have checked my code and corrected any misspellings

Allow defining shared memory size at runtime

---

CMakeLists.txt
Makefile
attach/CMakeLists.txt
runtime/src/bpftime_shm_internal.cpp

Sometimes `SPDLOG_LEVEL=debug` cannot be printed even if we build in Debug mode.

Fix: debug log cannot be print when build in debug mode

---

vm/llvm-jit/include/compat_llvm.hpp
vm/llvm-jit/src/compat/compat_llvm.cpp
vm/llvm-jit/src/llvm/compiler.cpp
vm/llvm-jit/src/llvm/llvm_jit_context.cpp
vm/llvm-jit/src/llvm/llvm_jit_context.hpp

This PR updated llvm-jit so it will execute lddw helpers (https://docs.kernel.org/bpf/standardization/instruction-set.html#id33) at runtime and hardcodes generated values into LLVM IR, thus reducing runtime oveahead
Also set default implementation for map_by_fd and map_by_idx: returning its input value
- One exception is that map_val won't be patched for AOT compilations, since AOT-ed programs could be migrated among processed, and map_val (a memory address) may be invalided among processes

llvm-jit: patch lddw helpers at compile time

---

.github/workflows/test-examples.yml
CMakeLists.txt
Makefile
README.md
attach/text_segment_transformer/agent-transformer.cpp
runtime/CMakeLists.txt
runtime/agent/agent.cpp
runtime/include/bpftime_config.hpp
runtime/include/bpftime_logger.hpp
runtime/include/bpftime_shm.hpp
runtime/object/bpf_object.cpp
runtime/src/bpf_helper.cpp
runtime/src/bpftime_config.cpp
runtime/src/bpftime_shm.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/src/bpftime_shm_json.cpp
runtime/src/handler/map_handler.cpp
runtime/syscall-server/CMakeLists.txt
runtime/syscall-server/syscall_context.cpp
runtime/syscall-server/syscall_context.hpp
runtime/syscall-server/syscall_server_main.cpp
runtime/syscall-server/syscall_server_utils.cpp
tools/cli/main.cpp

A draft version of logging. It implements:
- Log spdlogs to target from env var BPFTIME_LOG_OUTPUT. Default to be stderr. All logs from runtime (syscall_server, agent, agent-transformer) go to given target.
- Logs from client (cli/main.cpp) and ebpf program output untouched. I suppose ppl always want client feedback from stdout/err.
Used file but not named pipe. bpftime server should be similar to docker daemon, managing "services" of injected ebpf programs. The log should be persistent, reusable. 
Now usage:
```
kailian@ubt23:~/bpftime$ sudo BPFTIME_LOG_OUTPUT=skeleton_logging.out /home/kailian/.bpftime/bpftime -i /home/kailian/.bpftime load ./example/opensnoop/opensnoop\
PID    COMM              FD ERR PATH
^CINFO [40749]: Global shm destructed
kailian@ubt23:~/bpftime$ cat …
```

fix: log runtime output to env var "BPFTIME_LOG_OUTPUT"

---

.devcontainer/devcontainer.json
.github/dependabot.yml
.github/workflows/test-examples.yml
README.md
attach/base_attach_impl/CMakeLists.txt
attach/frida_uprobe_attach_impl/CMakeLists.txt
attach/syscall_trace_attach_impl/src/syscall_trace_attach_impl.cpp
benchmark/CMakeLists.txt
runtime/src/bpf_map/shared/perf_event_array_kernel_user.cpp
runtime/src/bpf_map/userspace/prog_array.cpp
vm/CMakeLists.txt

- Add PATH in README
- Add dev container
- Add syscall number defines
- Fix cmake version

fix: compile on old cmake version and add PATH

---

.github/workflows/test-attach.yml
.github/workflows/test-runtime.yml
.github/workflows/test-verifier.yml
attach/frida_uprobe_attach_impl/CMakeLists.txt
attach/syscall_trace_attach_impl/CMakeLists.txt
bpftime-verifier/CMakeLists.txt
runtime/unit-test/CMakeLists.txt

This pull request wants to merge a feature of testing, including
- support of lcov
- support of codecov

feat:add lcov and codecov support

---

.github/workflows/test-runtime.yml
README.md
benchmark/uprobe/uprobe.bpf.c

The runtime codecov CI has syntax error.

CI: fix runtime codecov

---

.github/workflows/test-examples.yml
.github/workflows/test-runtime.yml
attach/frida_uprobe_attach_impl/CMakeLists.txt
attach/syscall_trace_attach_impl/CMakeLists.txt
bpftime-verifier/CMakeLists.txt
runtime/src/bpf_map/map_common_def.hpp
runtime/src/bpf_map/userspace/array_map.cpp
runtime/src/bpf_map/userspace/per_cpu_array_map.cpp
runtime/src/bpf_map/userspace/per_cpu_hash_map.cpp
runtime/src/bpf_map/userspace/per_cpu_hash_map.hpp
runtime/src/bpf_map/userspace/var_hash_map.cpp
runtime/src/bpf_map/userspace/var_hash_map.hpp
runtime/src/handler/map_handler.cpp
runtime/unit-test/CMakeLists.txt
runtime/unit-test/maps/kernel_unit_tests.cpp
runtime/unit-test/maps/test_bpftime_hash_map.cpp
runtime/unit-test/maps/test_per_cpu_hash.cpp

This PR integrates some bpf unittests from kernel (https://elixir.bootlin.com/linux/latest/source/tools/testing/selftests/bpf) into bpftime.
These tests from `test_maps.c` are expected to work:
Note hash map tests are only implemented for var_size_hash_map_impl, also used pre-allocated nodes for performance increasing

feat: add unit tests from kernel

---

Dockerfile

The old Dockerfile uses `ubuntu:23.04` which is not an LTS version, and has been deprecated now

fix: docker ci unable to run

---

.github/workflows/test-runtime.yml
CMakeLists.txt
Makefile
benchmark/README.md
cmake/StandardSettings.cmake
runtime/src/bpf_helper.cpp
runtime/unit-test/CMakeLists.txt
runtime/unit-test/test_probe.cpp

We avoid core dump when accessing an illegal address (such as NULL). Now we will get different error code for such situation.

feat:Prevent segmentation fault in probe_read & probe_write

---

.github/workflows/test-attach.yml
.github/workflows/test-examples.yml
.github/workflows/test-runtime.yml
daemon/user/bpftime_driver.cpp
runtime/agent/agent.cpp
runtime/include/bpftime_config.hpp
runtime/include/bpftime_shm.hpp
runtime/src/bpftime_config.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/src/bpftime_shm_internal.hpp
runtime/syscall-server/syscall_context.cpp
runtime/syscall-server/syscall_server_utils.cpp
runtime/unit-test/CMakeLists.txt
runtime/unit-test/maps/test_external_map_ops.cpp
runtime/unit-test/test_config.cpp
tools/bpftimetool/main.cpp
tools/cli/main.cpp

In the previous implementation, field `logger_output_path` in `agent_config` was in type `std::string`, but this struct will be put on shared memory when setting `BPFTIME_LOG_OUTPUT` on server side. This will crash any agent who tries to use configuration from shared memory.
This PR updates it, making it use `boost_shm_string` when the config struct was transfered to shared memory.

fix: use boost_shm_string when an agent_config being setup on shared memory

---

.github/script/run_nginx_attach_example.py
.github/workflows/test-nginx-attach.yml
attach/CMakeLists.txt
attach/simple_attach_impl/CMakeLists.txt
attach/simple_attach_impl/simple_attach_impl.cpp
attach/simple_attach_impl/simple_attach_impl.hpp
example/attach_implementation/CMakeLists.txt
example/attach_implementation/controller/controller.cpp
example/attach_implementation/nginx_plugin_adaptor/nginx_plugin_adaptor.cpp
runtime/CMakeLists.txt

This PR adds a new attach type, named `simple_attach_impl`, which is a simple wrapper around `base_attach_impl`. By calling a function `add_simple_attach_impl_to_attach_ctx`, a user can simply register a single-instance, external event triggered attach implementation (such as an nginx url filter).
Behavior of the new attach wrapper can be seen at `example/attach_implementation/controller/controller.cpp`. Only need to provide a callback function (under this case).
This PR will also adds an unit test workflow to execute nginx attach.

Add simple attach impl to provide simpler way to register some basic attach impls

---

CITATION.cff
CLAUDE.md
README.md

This pull request updates the project's documentation to reflect the publication of the work in OSDI '25 and revises author affiliations and abstract details in the `CITATION.cff` file. Additionally, it updates a submodule reference. Below are the key changes:
* Updated references in `README.md` to replace mentions of the Arxiv preprint with the OSDI '25 paper, including links, descriptions, and citation details. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L14-R14) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L157-R157) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L222-R230)
* Added affiliations for authors in the `CITATION.cff` file and updated the abstract to …

Update CITATION.cff and README.md to reflect new paper

---

daemon/user/bpftime_driver.cpp
daemon/user/handle_bpf_event.cpp
runtime/agent/agent.cpp
runtime/include/bpftime_logger.hpp
runtime/src/bpf_helper.cpp
runtime/src/bpf_map/shared/array_map_kernel_user.cpp
runtime/src/bpftime_config.cpp
runtime/src/bpftime_shm_internal.cpp
runtime/syscall-server/syscall_context.cpp
runtime/syscall-server/syscall_server_main.cpp
tools/cli/main.cpp

There are two major issues during reattaching:
- `static int initialized = 0;` in `agent.cpp` won't be set to zero when detached
- spdlog logger will be double-initialized which cause an exception
This PR fixes them
Closes #415

fix: cleanup when reattach

---

runtime/src/handler/map_handler.cpp

When BPFTIME_ENABLE_CUDA_ATTACH=1, there are some compilation errors:
```
61.82 /bpftime/runtime/src/handler/map_handler.cpp: In member function 'int bpftime::bpf_map_handler::map_init(bpftime::managed_shared_memory&)':
61.82 /bpftime/runtime/src/handler/map_handler.cpp:807:25: warning: left operand of comma operator has no effect [-Wunused-value]
61.82   807 |                         "Map {} (nv_gpu_ringbuf_map_impl) has space for thread count {}",
61.82       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
61.82 /bpftime/runtime/src/handler/map_handler.cpp:808:70: error: expected ';' before ')' token
61.82   808 |                         container_name.c_str(), attr.gpu_thread_count);
61.82       | …
```

fix: Resolve compilation failure when BPFTIME_ENABLE_CUDA_ATTACH=1

---

attach/nv_attach_impl/nv_attach_impl.cpp
attach/nv_attach_impl/nv_attach_impl_patcher.cpp
example/gpu/cuda-counter/cuda_probe.bpf.c
example/gpu/kernelretsnoop/kernelretsnoop.bpf.c
example/gpu/launchlate/launchlate.bpf.c
example/gpu/mem_trace/mem_trace.bpf.c
example/gpu/threadhist/threadhist.bpf.c
runtime/include/bpftime_prog.hpp
runtime/src/attach/bpf_attach_ctx.cpp

In ths original CUDA attach design, an eBPF program with name ending with `__cuda` marks it a CUDA program. But libbpf will ignore characters if that name was too long, so sometimes a name like `trace_cuda_kernel__cuda` will be regarded as `trace_cuda_kern` by bpftime. In this way, bpftime will pass an empty eBPF program for memtrace programs, with prepending memtrace-specific trampoline, an eBPF program without `exit` instructions will be generated, leading to a basicblock without exit instructions in LLVM IR, stuck the LLVM optimizer.
This PR fixed the issue by using prefix `cuda__` to mark an eBPF program a CUDA program

gpu: fix memtrace example 
