eunomia-bpf/bpftime

.github/workflows/runtime.yml, .github/workflows/test-cli.yml, .github/workflows/test-verifier.yml, CITATION.cff, Makefile, documents/build-and-test.md
Fix build and test error of runtime ci.
=> ci: fix build error for runtime

.github/workflows/test-cli.yml, .github/workflows/test-ringbuf-and-opensnoop.yml, Makefile
=> Update a test workflow to test opensnoop and ringbuf

README.md, documents/build-and-test.md
- Fix README.md unused example test program name.
- Add description of toolchain version,and update build and install steps.
=> Update "README.md" and "documents/build-and-test.md"

runtime/agent/agent.cpp
This PR makes agent correctly handle the initialization of bpftime_shm and bpf_attach_ctx when using attach mode, thus makes attaching mode works properly.
Closes #35
=> runtime: fix an initializing bug when using attach mode

.github/workflows/docker.yml, Dockerfile
=> ci: add build and publish docker image

daemon/CMakeLists.txt, daemon/README.md, daemon/test/malloc.json, daemon/user/handle_bpf_event.cpp, runtime/include/bpftime_shm.hpp, runtime/src/attach/bpf_attach_ctx.cpp, runtime/src/bpftime_shm.cpp, runtime/src/bpftime_shm_internal.cpp, runtime/src/bpftime_shm_json.cpp, runtime/src/handler/map_handler.cpp, runtime/src/handler/map_handler.hpp, runtime/src/handler/perf_event_handler.hpp, runtime/src/handler/prog_handler.hpp, runtime/syscall-server/syscall_context.cpp, runtime/test/src/test_shm_progs_attach.cpp, runtime/test/src/test_shm_server.cpp
=> daemon: add doc and fix map type defs

README.md, daemon/README.md, runtime/src/handler/handler_manager.hpp
=> runtime: fix test for bad_alloc

README.md, example/bpftrace/README.md, example/bpftrace/bashreadline.bt, example/bpftrace/execsnoop.bt, example/bpftrace/gethostlatency.bt, example/bpftrace/killsnoop.bt, example/bpftrace/opensnoop.bt, example/bpftrace/sslsnoop.bt, example/bpftrace/statsnoop.bt, example/bpftrace/syncsnoop.bt, example/bpftrace/syscount.bt, example/bpftrace/threadsnoop.bt
=> examples: add examples from bpftrace

CODE_OF_CONDUCT.md
=> doc: Create CODE_OF_CONDUCT.md

.github/workflows/test-runtime.yml, README.md
- Hardware:
- Toolchain:
- SDK:
=> Docs: Add acknowledgement and fix ci 

.github/workflows/test-examples.yml, example/libbpf-tools/syscount/.gitignore, example/libbpf-tools/syscount/Makefile, example/libbpf-tools/syscount/README.md, example/libbpf-tools/syscount/errno_helpers.c, example/libbpf-tools/syscount/errno_helpers.h, example/libbpf-tools/syscount/maps.bpf.h, example/libbpf-tools/syscount/syscall_helpers.c, example/libbpf-tools/syscount/syscall_helpers.h, example/libbpf-tools/syscount/syscount.bpf.c, example/libbpf-tools/syscount/syscount.c, example/libbpf-tools/syscount/syscount.h, example/libbpf-tools/syscount/victim.cpp
Add syscount examples from bcc.
=> examples: add syscount

daemon/kernel/bpf_tracer.bpf.c, daemon/user/handle_bpf_event.cpp, documents/usage.md, example/sslsniff/README.md, runtime/src/bpf_map/userspace/array_map.hpp, runtime/src/bpf_map/userspace/hash_map.cpp, runtime/src/bpf_map/userspace/hash_map.hpp, runtime/src/bpftime_shm_internal.hpp, runtime/src/handler/map_handler.cpp, runtime/src/handler/map_handler.hpp
- fix unnecessary locks
- use spin lock instead of mutex
- add documents of how to use JIT
Fixes #76
=> docs: add documents of how to use JIT

.github/workflows/test-examples.yml, example/libbpf-tools/funclatency/.gitignore, example/libbpf-tools/funclatency/Makefile, example/libbpf-tools/funclatency/bits.bpf.h, example/libbpf-tools/funclatency/funclatency.bpf.c, example/libbpf-tools/funclatency/funclatency.c, example/libbpf-tools/funclatency/funclatency.h, example/libbpf-tools/funclatency/victim.cpp
Adds example funclatency, an example to measure function call timing
=> example: add funclatency from bcc/libbpf-tools

benchmark/README.md, benchmark/run_benchmark.py, benchmark/uprobe/uprobe.c
Adds a micro benchmark runner that could automatically run uprobe (kernel and userspace) and embed-vm micro benchmarks, and give out statistics
=> benchmark: add micro benchmark runner

Dockerfile
Remove rust toolchain in docker image to make it smaller.
=> docker: remove rust toolchain

.github/workflows/test-aot-cli.yml, .github/workflows/test-runtime.yml, daemon/test/CMakeLists.txt, runtime/src/bpf_map/userspace/prog_array.cpp, runtime/unit-test/CMakeLists.txt, runtime/unit-test/attach/test_filter_attach_with_override.cpp, runtime/unit-test/attach/test_replace_attach_with_override.cpp, runtime/unit-test/attach_with_ebpf/test_attach_filter_with_ebpf.cpp, runtime/unit-test/tailcall/test_user_to_kernel_tailcall.cpp, vm/llvm-jit/CMakeLists.txt, vm/llvm-jit/unit-test/CMakeLists.txt
Closes #159 
Using Fedora 39 docker image to run these tests
=> ci: make all tests run under fedora(AOT & runtime)

tools/cli-cpp/main.cpp, vm/cli/main.cpp
Fixes #179 
- Hardware:
- Toolchain:
- SDK:
=> cli: Support set spdlog log level by using env for bpftime cli

vm/llvm-jit/example/main-bpf-conformance.cpp
=> vm: fix compile error on g++ 10.3.1

.github/workflows/test-aot-cli.yml, .github/workflows/test-examples.yml, .github/workflows/test-llvm-jit.yml, .github/workflows/test-vm.yml, vm/llvm-jit/CMakeLists.txt
Fixes #187 
In this PR, I make some changes following below:
1. Use the LLVM managed by the system package manager
2. Add `LLVM_FIND_PATH` to let people customize the LLVM path themself
3. Add `ENABLE_LLVM_SHARED` for some special distributions which are make the LLVM all dynamic lib (like Arch Linux, FYI  https://gitlab.archlinux.org/archlinux/packaging/packages/llvm/-/commit/3e452a15b68d156a9ef5608e8f6e1870d192d954)
- Hardware:
- Toolchain:
- SDK:
=> ci: Fix CMakeLists.txt for llvm-jit to allow user define the llvm path

.github/workflows/build-benchmarks.yml, .github/workflows/docker.yml, .github/workflows/test-aot-cli.yml, .github/workflows/test-examples.yml, .github/workflows/test-llvm-jit.yml, .github/workflows/test-runtime.yml, .github/workflows/test-verifier.yml, .github/workflows/test-vm.yml, Dockerfile.fedora, Dockerfile.ubuntu
- Hardware:
- Toolchain:
- SDK:
=> CI: clean the CI workflow by using Dockerfile

CMakeLists.txt, Makefile
Fix #174 add more info to help the debug action
=> ci: Release binary with RelWithDebInfo and support "no-omit-frame-pointer" to keep the frame pointer

CONTRIBUTING.md
Link to create custom issue report was broken in contributors guidelines.
So, gave it a quick fix.
Fixes #224 
- [x ] This change requires a documentation update
- Hardware:
- Toolchain:
- SDK:
=> fix: Updated link in the contributor guidelines

.github/workflows/test-attach.yml, .github/workflows/test-llvm-jit.yml
Fixes #236 
This change adds a CI job in github workflow to run 
- bpftime_frida_uprobe_attach_tests
- bpftime_syscall_trace_attach_tests
=> workflow to run attach tests

CMakeLists.txt, Dockerfile, Makefile, vm/llvm-jit/CMakeLists.txt
Fixes #262  (issue)
- [✅] New feature (non-breaking change which adds functionality)
- [✅] This change requires a documentation update
```
cmake -DCMAKE_PREFIX_PATH=/usr/include/llvm -DBPFTIME_LLVM_JIT=YES -DBPFTIME_ENABLE_UNIT_TESTING=YES -DCMAKE_BUILD_TYPE=Release -B build
cmake --build build --config RelWithDebInfo --target bpftime_runtime_tests
sudo ./build/runtime/unit-test/bpftime_runtime_tests
```
Log:
```
bpftime_runtime_tests is a Catch2 v3.4.0 host application.
Run with -? for options
-------------------------------------------------------------------------------
Test tail calling from userspace to kernel
-------------------------------------------------------------------------------
/workdir/bpftime/runtime/unit-test/tailcall/test_user_to_kernel_tailcall.cpp:18 …
```
=> runtime: make LLVM JIT Compiled by default

CMakeLists.txt, Makefile, daemon/user/bpf_tracer.cpp, runtime/src/bpf_helper.cpp, tools/bpftimetool/main.cpp
Replaced the clock_gettime with std::chrono 
Fixes #283 
- [✅] New feature (non-breaking change which adds functionality)
- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have checked my code and corrected any misspellings
=> Add feature Use std::chrono instead of clock_gettime

.github/workflows/build-benchmarks.yml, .gitignore, attach/frida_uprobe_attach_impl/src/frida_attach_utils.cpp, attach/frida_uprobe_attach_impl/src/frida_uprobe_attach_impl.cpp, benchmark/.gitignore, benchmark/Makefile, benchmark/README.md, benchmark/run_benchmark.py, runtime/agent/agent.cpp, runtime/src/attach/bpf_attach_ctx.cpp, runtime/src/bpftime_prog.cpp, runtime/syscall-server/CMakeLists.txt, runtime/syscall-server/syscall_server_main.cpp, tools/bpftimetool/README.md, vm/compat/include/bpftime_vm_compat.hpp
- Improve error message when attach to unrelated process
- Improve syscall server error handle
Now, if one uprobe attach failed, it will continue trying to attach other uprobes.
=> fix: improve error message and handling in syscall-server

README.md
- Hardware:
- Toolchain:
- SDK:
=> docs: add notice

CMakeLists.txt
fix compile bug of ubpf & llvm-jit
- Hardware:
- Toolchain:
- SDK:
=> fix ubpf & llvm-jit compile error

codecov.yml
This pull request introduces a configuration file for Codecov to manage code coverage reporting and thresholds. The most important change is the addition of the `codecov.yml` file to define ignored directories and set coverage thresholds for the project and patches.
* [`codecov.yml`](diffhunk://#diff-3e878d9bdc47f29a0ab909a7db939acf08d2d2f1aaba81e6f897b32361fa40dbR1-R17): Added a configuration file to ignore the `third_party` directory and define coverage thresholds. The project allows a 0.5% drop in coverage from the base commit, and similar thresholds are applied to patches.
=> Add codecov config file and threshold

README.md
=> Fix a typo in README [skip ci]

.gitignore, benchmark/syscount/Makefile, example/attach_implementation/benchmark/README.md, example/attach_implementation/benchmark/example_benchmark_results.json, example/attach_implementation/benchmark/run_benchmark.py, example/attach_implementation/benchmark/visualization.py
This pull request introduces updates to the benchmark framework for evaluating Nginx modules, including adjustments to benchmark parameters, the addition of a JSON results file, and a new visualization script for performance metrics. The most important changes include updating benchmark parameters for more iterations and connections, adding a JSON output for detailed results, and introducing a visualization script to generate a performance comparison chart.
* Updated benchmark parameters in `run_benchmark.py` to increase the duration, reduce the number of connections and threads, and increase the number of iterations for more robust testing. (`example/attach_implementation/benchmark/run_benchmark.py`)
* Added a JSON results file (`example_benchmark_results.json`) to store detailed …
=> benchmark: add new visualization script for performance metrics
